#pragma once

#define GENERALS_ONLINE

//#define GENERALS_ONLINE_GAMETYPE_GENERALS
#define GENERALS_ONLINE_GAMETYPE_ZEROHOUR

//#define GENERALS_ONLINE_BRANCH_JMARSHALL
#define GENERALS_ONLINE_BRANCH_SUPERHACKERS

#define RTS_MULTI_INSTANCE 1

#define ALLOW_NON_PROFILED_LOGIN 1

#define NEXT_GEN_MP 1

// NOTE: This is a test product. We change these to a real product for releases
#define NGMP_EOS_PRODUCT_ID "f94032c81d28492789089d7d0d0109dd"
#define NGMP_EOS_SANDBOX_ID "36bf3bb683954103b8e12098da4c2bef"
#define NGMP_EOS_ENCRYPTION_KEY "397b401e2dd62f74651f6499e2babc5e522ccf5aedc5bfeec182077882d0add4"
#define NGMP_EOS_DEPLOYMENT_ID "7e3a382c23a04467bd27ac5c8989cb6a"
#define NGMP_EOS_CLIENT_ID "xyza7891dh9LSQusLBO2cNQrXu2O8MBH"
#define NGMP_EOS_CLIENT_SECRET "84dDmfcg9YYtu7rvm9sPZbdSQeZfaUDlmOzsJ8P12bM"

#define NATPMP_STATICLIB 1

#define GENERALS_ONLINE_VERSION 1
#define GENERALS_ONLINE_NET_VERSION 1
#define GENERALS_ONLINE_SERVICE_VERSION 1

// annoying game assertions, we'll catch real things in the debugger
#define DISABLE_DEBUG_CRASHING 1

//#define GENERALS_ONLINE_TEST_MAP_TRANSFER 1

//#define NETWORK_CONNECTION_DEBUG 1

//#define GENERALS_ONLINE_RUN_FAST 1

#define GENERALS_ONLINE_HIGH_FPS_SERVER 1
#define GENERALS_ONLINE_HIGH_FPS_LIMIT 60

// useful for testing release builds with multiple logins
//#define GENERALS_ONLINE_DONT_SAVE_CREDENTIALS 1